databases:
  - name: scribe-notes-db
    plan: free
    databaseName: scribe_notes
    user: scribe_notes

services:
  - type: web
    name: scribe-notes
    runtime: python
    plan: free
    buildCommand: bash ./build.sh
    startCommand: python -m gunicorn journal.asgi:application -k uvicorn.workers.UvicornWorker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: scribe-notes-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: 4
      - key: GOOGLE_OAUTH_CLIENT_ID
        sync: false
      - key: GOOGLE_OAUTH_CLIENT_SECRET
        sync: false
